//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by 1p1Emu.rc
//
#define IDD_MY1P1EMU_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDS_WELCOME_MSG                 129
#define IDS_BLOCKING_SHOUT              130
#define IDS_BLOCKING_PM                 131
#define IDS_BLOCKING_PARTY              132
#define IDS_POLICE_CHAT                 133
#define IDS_USER_TOO_LOW_LEVEL_FOR_SHOUT 134
#define IDS_USER_NOT_ENOUGH_STAMINA_FOR_SHOUT 135
#define IDS_PM_USER_NOT_CONNECTED_NOW   136
#define IDS_CANNOT_PM_SELF              137
#define IDS_USER_REJECT_WHISPER         138
#define IDS_OTHER_USER_REJECT_WHISPER   139
#define IDS_EQUIP_OFF_INV_FULL          140
#define IDS_THROW_BARR                  141
#define IDS_THROW_ITEM                  142
#define IDS_THROW_ITEMS                 143
#define IDS_PICKUP_WEIGHT_FULL          144
#define IDS_BELT_FULL                   145
#define IDS_PICKUP_BARR                 146
#define IDS_PICKUP_ITEM                 147
#define IDS_PICKUP_ITEMS                148
#define IDS_USER_CURRENT_USER_COUNT     149
#define IDS_BUY_NOT_ENOUGH_WEIGHT       150
#define IDS_TEST                        150
#define IDS_BUY_NOT_ENOUGH_BARR         151
#define IDS_BUY_NOT_ENOUGH_POS          152
#define IDS_INV_FULL                    153
#define IDS_TAKESTORAGE_WEIGHT_FULL     154
#define IDS_USER_ITEM_CANNOT_EQUIP      155
#define IDS_USER_ITEM_STILL_EQUIPPED    156
#define IDS_USER_ITEM_CANNOT_USE        157
#define IDS_GM_MSG_ATTACK_DELAY         158
#define IDS_GM_MSG_ATTACK_INFO          159
#define IDS_GM_MSG_ATTACK_DAMAGE        160
#define IDS_USER_STAFF                  161
#define IDS_GM_MSG_PLUS_WEAPON_EXP      162
#define IDS_USER_STR_INC                163
#define IDS_USER_DEX_INC                164
#define IDS_USER_INT_INC                165
#define IDS_USER_STR_DEC                166
#define IDS_USER_DEX_DEC                167
#define IDS_USER_INT_DEC                168
#define IDS_USER_WIS_DEC                169
#define IDS_USER_CON_DEC                170
#define IDS_USER_CHA_DEC                171
#define IDS_USER_MAGIC_MORAL_LOW        172
#define IDS_USER_MAGIC_MORAL_HIGH       173
#define IDS_USER_MAGIC_SKILL_LOW        174
#define IDS_USER_STORAGE_SPACE_INC      175
#define IDS_USER_ITEM_BADLY_DMG         176
#define IDS_USER_ITEM_ABOUT_TO_BREAK    177
#define IDS_USER_ITEM_DESTROYED         178
#define IDS_USER_BLOCKING_PARTY         179
#define IDS_USER_ACCEPTING_PARTY        180
#define IDS_USER_PARTY_DISBANDED        181
#define IDS_USER_PARTY_LEAVE            182
#define IDS_USER_NOT_CONNECTED_NOW      183
#define IDS_USER_CANNOT_PARTY_OTHER_RACE 184
#define IDS_USER_BLOCKING_PARTY_INVITE  185
#define IDS_USER_PARTY_REACHED_MAX_ALLOWED 186
#define IDS_USER_ALREADY_IN_PARTY       187
#define IDS_USER_PARTY_WITHDRAW         188
#define IDS_USER_PARTY_CREATED          189
#define IDS_USER_PARTY_JOIN             190
#define IDS_USER_CURRENTLY_PARTY_WITH   191
#define IDS_USER_CANNOT_PK_LEVEL_BELOW  192
#define IDS_USER_ATTACK_RATE            193
#define IDS_USER_REVIVE_LOW_SKILL       194
#define IDS_USER_REVIVE_BY_ITEM         195
#define IDS_GM_MSG_MAGIC_DEF            196
#define IDS_GM_MSG_DEFENSE              197
#define IDS_CHANGEOTHERITEM_WEIGHT_FULL 198
#define IDS_GM_MSG_MAGIC_ATTACK_INFO    199
#define IDS_GM_MSG_MAGIC_AT             200
#define IDS_GM_MSG_MORAL_EXP            201
#define IDS_GM_MSG_PLUS_MAGIC_EXP       202
#define IDS_GM_KICK_USER                203
#define IDS_USER_CANNOT_SELL_ITEM       204
#define IDS_CLASS_WAR_BEGUN             205
#define IDS_CLASS_WAR_END_HSOMA         206
#define IDS_CLASS_WAR_END_DSOMA         207
#define IDS_TRADER_EXCHANGE_NO_INV_SPACE 208
#define IDS_TRADER_EXCHANGE_NOT_ENOUGH_ITEM 209
#define IDS_TRADER_EXCHANGE_WEIGHT_FULL 210
#define IDS_MAKE_GUILD                  211
#define IDS_GUILD_USER_APPLY            212
#define IDS_GUILD_APPLICATION_ACCEPTED  213
#define IDS_GUILD_USER_JOIN             214
#define IDS_GUILD_APPLICATION_REJECTED  215
#define IDS_GUILD_LEADER_CHANGE         216
#define IDS_GUILD_USER_EXPELLED         217
#define IDS_GUILD_USER_WITHDRAW         218
#define IDS_GM_MSG_SPECIAL_ATTACK_INFO  219
#define IDS_USER_NEED_SCROLL_FOR_SHOUT  220
#define IDS_TRADER_EXCHANGE_RECEIEVE_ITEM 221
#define IDS_TRADER_EXCHANGE_RECEIEVE_ITEMS 222
#define IDS_USER_HAS_POS                223
#define IDS_ZONESHOUT_REFUSE            224
#define IDS_ZONESHOUT_ALLOW             225
#define IDS_BLOCK_PM                    226
#define IDS_ALLOW_PM                    227
#define IDS_CANNOT_THROW_ITEM           228
#define IDS_USER_WAREHOUSE_FULL         229
#define IDS_NOT_ENOUGH_WEIGHT           230
#define IDS_GM_MSG_SPECIAL_ATTACK_CANCEL 231
#define IDS_USER_DOUBLE_CHAR            232
#define IDS_ALREADY_IN_GUILD_WAR        233
#define IDS_GUILD_WAR_ONLY_LEADER       234
#define IDS_GUILD_WAR_CANNOT_FIND_GUILD 235
#define IDS_GUILD_WAR_CANNOT_FIND_GUILD_LEADER 236
#define IDS_GUILD_WAR_CANNOT_WAR_OTHER_RACE 237
#define IDS_GUILD_WAR_OTHER_GUILD_IN_WAGER 238
#define IDS_GUILD_WAR_CANNOT_WAR_OWN_GUILD 239
#define IDS_USER_HIDE                   240
#define IDS_USER_APPEAR                 241
#define IDS_TRADE_CANCEL                242
#define IDS_GUILD_STORAGE_IN_USE        243
#define IDS_GUILD_STORAGE_FULL          244
#define IDS_CANNOT_PLACE_GUILD_STORAGE  245
#define IDS_USER_NO_PERMISSION_USE      246
#define IDS_GUILDWAR_START              247
#define IDS_GUILDWAR_END                248
#define IDS_GM_INV_CHANGED              249
#define IDS_GM_INV_RESTORED             250
#define IDS_ITEM_MORAL_HIGH             251
#define IDS_CANNOT_TRADE_ITEM           252
#define IDS_TRADE_NO_INV_SPACE          253
#define IDS_TRADE_WEIGHT_FULL           254
#define IDS_GUILD_TOWN_WAR_TYT_BEGUN    255
#define IDS_GUILD_TOWN_WAR_IC_BEGUN     256
#define IDS_GUILD_TOWN_WAR_END          257
#define IDS_GUILD_TOWN_WAR_TYT_SOON     258
#define IDS_GUILD_TOWN_WAR_IC_SOON      259
#define IDS_GUILD_TOWN_WAR_IN_PROGRESS  260
#define IDS_CANNOT_FIND_USER            261
#define IDS_GUILD_MEMBERS_ONLY          262
#define IDS_GUILD_TOWN_OWNER_ONLY       263
#define IDS_GUILD_WAR_GUILD_TOWN_WAR    264
#define IDS_GUILD_WAR_NOT_ENOUGH_BARR   265
#define IDS_USER_WIS_INC                448
#define IDS_USER_CON_INC                450
#define IDS_USER_CHA_INC                452
#define IDS_USER_BLACK_MAGIC            454
#define IDS_USER_BLUE_MAGIC             456
#define IDS_USER_WHITE_MAGIC            458
#define IDS_USER_SWORD                  460
#define IDS_USER_SPEAR                  462
#define IDS_USER_AXE                    464
#define IDS_USER_BOW                    466
#define IDS_USER_KNUCKLE                468
#define IDS_USER_WEAPON                 470
#define IDS_USER_ARMOR                  472
#define IDS_USER_ACC                    474
#define IDS_USER_POT                    476
#define IDS_USER_COOK                   478
#define IDS_USER_INC                    479
#define IDS_USER_DEC                    480

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        163
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
